modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="quark_framed_glass_ct.png"
authors="Michael Brylevskii"
displayURL="https://github.com/michaelbrylevskii/quark-framed-glass-ct"
issueTrackerURL="https://github.com/michaelbrylevskii/quark-framed-glass-ct/issues"
description='''Client-only cross-color connected mosaic rendering for Quark framed-glass blocks and panes. No separate resource pack required.'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="quark"
type="required"
versionRange="[4.1-480,4.2)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="fusion"
type="required"
versionRange="[1.3.2,1.4)"
ordering="AFTER"
side="CLIENT"
